/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spencedalley' at '9/17/16 1:58 PM' with Gradle 2.14.1
 *
 * @author spencedalley, @date 9/17/16 1:58 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
